name = "database-api-service"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

type = "worker"
main = "src/index.js"
binding = [
  { name = "DB_A_URL", type = "secret" },
  { name = "DB_B_URL", type = "secret" },
  { name = "API_TOKEN", type = "secret" },
  { name = "STRUCTURE_API_KEY", type = "secret" }
]

[vars]
NODE_ENV = "production"

[build]
command = "npm install"
